# CONFIGURACIÓN ULTRA-ROBUSTA CON TU NUEVO USUARIO SQL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_Test_Allport;encrypt=false;trustServerCertificate=true;
spring.datasource.username=gessan
spring.datasource.password=gess123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diseniowebproyecto@gmail.com
spring.mail.password=smng lrgv iysu hsws
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true